output "ssh_key_id" {
  description = "ID of the Hetzner Cloud SSH key."
  value       = local.effective_key.id
}

output "ssh_key_name" {
  description = "Name of the SSH key."
  value       = local.effective_key.name
}

output "ssh_key_fingerprint" {
  description = "Fingerprint of the SSH key."
  value       = local.effective_key.fingerprint
}

output "ssh_key_labels" {
  description = "Labels applied to the SSH key."
  value       = local.effective_key.labels
}

output "public_key_openssh" {
  description = "Public key in OpenSSH format."
  value       = local.effective_key.public_key
  sensitive   = true
}

output "private_key_pem" {
  description = "Private key in PEM format. Only available when key was generated by this module."
  value       = var.create_key && var.public_key == null ? one(tls_private_key.this).private_key_pem : null
  sensitive   = true
}

output "private_key_openssh" {
  description = "Private key in OpenSSH format. Only available when key was generated by this module."
  value       = var.create_key && var.public_key == null ? one(tls_private_key.this).private_key_openssh : null
  sensitive   = true
}

output "private_key_file_path" {
  description = "Path to the saved private key file. Only available when save_private_key_locally is true."
  value       = var.save_private_key_locally && local.should_save_locally ? local.private_key_filename : null
  sensitive   = true
}

output "public_key_file_path" {
  description = "Path to the saved public key file. Only available when save_private_key_locally is true."
  value       = var.save_private_key_locally && local.should_save_locally ? local.public_key_filename : null
  sensitive   = true
}
